name: Zariz
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: '17.0'
packages:

  Popovers:
    url: https://github.com/aheze/Popovers
    from: 1.0.4
  AlertToast:
    url: https://github.com/elai950/AlertToast
    from: 1.3.0
  Shimmer:
    url: https://github.com/markiv/SwiftUI-Shimmer
    from: 1.5.1
  Lottie:
    url: https://github.com/airbnb/lottie-spm
    from: 4.4.0
settings:
  base:
    SWIFT_VERSION: '6.0'
    SWIFT_STRICT_CONCURRENCY: complete
    DEAD_CODE_STRIPPING: YES
    VALIDATE_WORKSPACE: YES
    PRODUCT_BUNDLE_IDENTIFIER: com.example.zariz
    INFOPLIST_FILE: Zariz/Supporting/Info.plist
targets:
  Zariz:
    type: application
    platform: iOS
    sources:
      - path: Zariz
    resources:
      - path: Zariz/Resources
    settings:
      base:
        PRODUCT_NAME: Zariz
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    preBuildScripts: []
    postCompileScripts: []
    dependencies:

      - package: Popovers
        product: Popovers
      - package: AlertToast
        product: AlertToast
      - package: Shimmer
        product: Shimmer
      - package: Lottie
        product: Lottie
  ZarizTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ZarizTests
    settings:
      base:
        TEST_HOST: ""
    dependencies:
      - target: Zariz
  ZarizUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ZarizUITests
    dependencies:
      - target: Zariz
