name: Zariz
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: '17.0'
settings:
  base:
    SWIFT_VERSION: '6.0'
    PRODUCT_BUNDLE_IDENTIFIER: com.example.zariz
    INFOPLIST_FILE: Zariz/Supporting/Info.plist
targets:
  Zariz:
    type: application
    platform: iOS
    sources:
      - path: Zariz
    settings:
      base:
        PRODUCT_NAME: Zariz
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    preBuildScripts: []
    postCompileScripts: []
  ZarizTests:
    type: bundle.unit-test
    platform: iOS
    sources: []
    settings:
      base:
        TEST_HOST: ""
    dependencies:
      - target: Zariz
  ZarizUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: []
    dependencies:
      - target: Zariz
