default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(
      scheme: "Zariz",
      device: "iPhone 15",
      clean: true
    )
  end

  desc "Build app"
  lane :build do
    build_app(
      scheme: "Zariz",
      export_method: "app-store"
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "Zariz",
      export_method: "app-store"
    )
    upload_to_testflight(skip_submission: true)
  end
end

